language: node_js
node_js:
 - "4"
 - "6"
 - "7"
 - "8"
 - "9"
 - "10"
before_install:
- yarn run lint
install:
- yarn install
script:
- yarn run compile
- yarn run test

jobs:
  include:
    - stage: after_success
      script:
        - yarn install
        - yarn run compile
        - yarn run coveralls
      node_js: 9

