language: node_js
node_js:
 - "8"
 - "10"
 - "12"
 - "14"
install:
- yarn install
script:
- yarn run lint
- yarn run compile
- yarn run test

jobs:
  include:
    - stage: after_success
      script:
        - yarn install
        - yarn run compile
        - yarn run coveralls
      node_js: 12

